cmake_minimum_required(VERSION 3.10)

project(CPP_SQL LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# Collect all source files
file(GLOB_RECURSE SOURCES src/*.cpp)

add_executable(CPP_SQL ${SOURCES})

# Tell compiler where headers are
target_include_directories(CPP_SQL PRIVATE include)